import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#005762",
        outline: "#72757d",
        "on-tertiary-fixed": "#00055d",
        "on-primary-fixed": "#003840",
        "on-error-container": "#ffa8a3",
        "secondary-fixed": "#c3f400",
        "surface-container-highest": "#20262f",
        "surface-variant": "#20262f",
        "tertiary-dim": "#8d96f4",
        "on-secondary": "#455900",
        "surface-container-high": "#1b2028",
        "tertiary-fixed-dim": "#929bfa",
        "tertiary-container": "#929bfa",
        error: "#ff716c",
        "on-error": "#490006",
        "primary-dim": "#00d4ec",
        "error-dim": "#d7383b",
        "secondary-container": "#506600",
        "surface-bright": "#262c36",
        "surface-tint": "#81ecff",
        "secondary-fixed-dim": "#b7e500",
        "on-surface": "#f1f3fc",
        "on-primary-container": "#004d57",
        secondary: "#c3f400",
        primary: "#81ecff",
        "surface-dim": "#0a0e14",
        "surface-container": "#151a21",
        surface: "#0a0e14",
        "on-tertiary-fixed-variant": "#252e88",
        "on-primary": "#005762",
        "surface-container-lowest": "#000000",
        "primary-fixed-dim": "#00d4ec",
        "on-secondary-fixed-variant": "#4e6300",
        background: "#0a0e14",
        "outline-variant": "#44484f",
        "error-container": "#9f0519",
        "inverse-primary": "#006976",
        "inverse-on-surface": "#51555c",
        "primary-fixed": "#00e3fd",
        tertiary: "#a2aaff",
        "primary-container": "#00e3fd",
        "surface-container-low": "#0f141a",
        "inverse-surface": "#f8f9ff",
        "on-tertiary": "#1b247f",
        "on-tertiary-container": "#0b1574",
        "tertiary-fixed": "#a2aaff",
        "on-background": "#f1f3fc",
        "on-secondary-fixed": "#354500",
        "on-secondary-container": "#efffbc",
        "secondary-dim": "#b7e500",
        "on-surface-variant": "#a8abb3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["Space Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [forms],
}
