const LEAGUE_KEY = "egypt";

const EGYPT_LEAGUE_TEAMS = [
  {
    team: "Cairo Warriors",
    tier: "Top",
    style: "Attacking",
    players: [
      { name: "Ahmed El-Sayed", pos: "ST", rating: 84 },
      { name: "Mahmoud Hassan", pos: "LW", rating: 81 },
      { name: "Mostafa Kamel", pos: "CM", rating: 79 },
      { name: "Karim Fathy", pos: "RB", rating: 77 },
      { name: "Hossam Farouk", pos: "GK", rating: 82 },
    ],
  },
  {
    team: "Nile Kings",
    tier: "Top",
    style: "Balanced",
    players: [
      { name: "Omar Abdelrahman", pos: "CAM", rating: 85 },
      { name: "Youssef Nabil", pos: "CB", rating: 82 },
      { name: "Tarek Mahmoud", pos: "CDM", rating: 80 },
      { name: "Ibrahim Adel", pos: "RW", rating: 83 },
      { name: "Wael Fawzy", pos: "CB", rating: 81 },
    ],
  },
  {
    team: "Alexandria Waves",
    tier: "Top",
    style: "Defensive",
    players: [
      { name: "Hossam El-Gohary", pos: "GK", rating: 84 },
      { name: "Samy Farouk", pos: "CM", rating: 78 },
      { name: "Khaled Mostafa", pos: "LB", rating: 76 },
      { name: "Amr Samir", pos: "ST", rating: 82 },
      { name: "Fady Nasser", pos: "CB", rating: 80 },
    ],
  },
  {
    team: "Delta Eagles",
    tier: "Mid",
    style: "Balanced",
    players: [
      { name: "Mohamed Salahy", pos: "RW", rating: 78 },
      { name: "Ahmed Shaban", pos: "CM", rating: 75 },
      { name: "Ali Gamal", pos: "CB", rating: 77 },
      { name: "Yassin Tarek", pos: "ST", rating: 76 },
      { name: "Hany Adel", pos: "GK", rating: 74 },
    ],
  },
  {
    team: "Pharaohs Club",
    tier: "Mid",
    style: "Attacking",
    players: [
      { name: "Karim Salah", pos: "ST", rating: 79 },
      { name: "Maher Ibrahim", pos: "CAM", rating: 77 },
      { name: "Omar Fathi", pos: "RB", rating: 75 },
      { name: "Sherif Adel", pos: "CM", rating: 74 },
      { name: "Mostafa Nabil", pos: "GK", rating: 73 },
    ],
  },
  {
    team: "Upper Egypt SC",
    tier: "Mid",
    style: "Defensive",
    players: [
      { name: "Hassan Ali", pos: "CB", rating: 78 },
      { name: "Wael Samir", pos: "CDM", rating: 76 },
      { name: "Ibrahim Taha", pos: "LB", rating: 74 },
      { name: "Mahmoud Fathy", pos: "ST", rating: 75 },
      { name: "Khaled Youssef", pos: "GK", rating: 74 },
    ],
  },
  {
    team: "Canal Fighters",
    tier: "Mid",
    style: "Balanced",
    players: [
      { name: "Tamer Hossam", pos: "RW", rating: 76 },
      { name: "Nader Farid", pos: "CM", rating: 74 },
      { name: "Ahmed Ragab", pos: "CB", rating: 75 },
      { name: "Omar Zaki", pos: "ST", rating: 77 },
      { name: "Fathi Adel", pos: "GK", rating: 73 },
    ],
  },
  {
    team: "Red Desert FC",
    tier: "Low",
    style: "Defensive",
    players: [
      { name: "Hany Khaled", pos: "CB", rating: 72 },
      { name: "Yasser Adel", pos: "CDM", rating: 70 },
      { name: "Mohamed Hamdy", pos: "LB", rating: 71 },
      { name: "Ali Tarek", pos: "ST", rating: 73 },
      { name: "Samir Fawzi", pos: "GK", rating: 72 },
    ],
  },
  {
    team: "Blue Nile FC",
    tier: "Low",
    style: "Balanced",
    players: [
      { name: "Ahmed Mostafa", pos: "RW", rating: 73 },
      { name: "Hossam Ibrahim", pos: "CM", rating: 71 },
      { name: "Karim Nasser", pos: "CB", rating: 72 },
      { name: "Wael Hassan", pos: "ST", rating: 74 },
      { name: "Tarek Ali", pos: "GK", rating: 70 },
    ],
  },
  {
    team: "Golden Pyramids",
    tier: "Top",
    style: "Attacking",
    players: [
      { name: "Ibrahim Samy", pos: "ST", rating: 85 },
      { name: "Ahmed Fathy", pos: "CM", rating: 82 },
      { name: "Mahmoud Nasser", pos: "CAM", rating: 83 },
      { name: "Hossam Ali", pos: "RB", rating: 79 },
      { name: "Karim Adel", pos: "GK", rating: 81 },
    ],
  },
  {
    team: "Suez Mariners",
    tier: "Mid",
    style: "Balanced",
    players: [
      { name: "Tarek Hassan", pos: "CM", rating: 76 },
      { name: "Omar Nabil", pos: "RW", rating: 75 },
      { name: "Fady Adel", pos: "CB", rating: 74 },
      { name: "Ahmed Samir", pos: "ST", rating: 77 },
      { name: "Mahmoud Khaled", pos: "GK", rating: 73 },
    ],
  },
  {
    team: "Sinai Stars",
    tier: "Low",
    style: "Defensive",
    players: [
      { name: "Ali Farouk", pos: "CB", rating: 71 },
      { name: "Hassan Samy", pos: "CDM", rating: 70 },
      { name: "Mostafa Zaki", pos: "LB", rating: 72 },
      { name: "Karim Fathy II", pos: "ST", rating: 73 },
      { name: "Youssef Adel", pos: "GK", rating: 71 },
    ],
  },
  {
    team: "Delta Lions",
    tier: "Mid",
    style: "Attacking",
    players: [
      { name: "Ahmed Yassin", pos: "LW", rating: 78 },
      { name: "Mahmoud Taha", pos: "CAM", rating: 76 },
      { name: "Omar Samy", pos: "CM", rating: 75 },
      { name: "Ali Fathy", pos: "RB", rating: 74 },
      { name: "Hossam Khaled", pos: "GK", rating: 73 },
    ],
  },
  {
    team: "Cairo Falcons",
    tier: "Top",
    style: "Balanced",
    players: [
      { name: "Ibrahim Hassan", pos: "ST", rating: 84 },
      { name: "Ahmed Nabil", pos: "RW", rating: 82 },
      { name: "Mostafa Ali", pos: "CM", rating: 80 },
      { name: "Tarek Samir", pos: "CB", rating: 81 },
      { name: "Wael Hassan II", pos: "GK", rating: 82 },
    ],
  },
  {
    team: "Giza Titans",
    tier: "Mid",
    style: "Physical",
    players: [
      { name: "Ramy Saad", pos: "ST", rating: 78 },
      { name: "Hany Magdy", pos: "CDM", rating: 76 },
      { name: "Mostafa Emad", pos: "CB", rating: 75 },
      { name: "Omar Hamdy", pos: "RB", rating: 74 },
      { name: "Ahmed Helmy", pos: "GK", rating: 74 },
    ],
  },
  {
    team: "Luxor Legends",
    tier: "Low",
    style: "Balanced",
    players: [
      { name: "Adel Mokhtar", pos: "ST", rating: 73 },
      { name: "Khaled Hany", pos: "CM", rating: 71 },
      { name: "Mahmoud Saber", pos: "CB", rating: 70 },
      { name: "Yasser Mohamed", pos: "LB", rating: 69 },
      { name: "Fady Ibrahim", pos: "GK", rating: 70 },
    ],
  },
  {
    team: "Port Said Pirates",
    tier: "Mid",
    style: "Balanced",
    players: [
      { name: "Tarek Abdelaziz", pos: "RW", rating: 77 },
      { name: "Sherif Youssef", pos: "CM", rating: 75 },
      { name: "Omar Ramadan", pos: "CB", rating: 76 },
      { name: "Ahmed Fawzy", pos: "ST", rating: 78 },
      { name: "Hossam Rashed", pos: "GK", rating: 74 },
    ],
  },
  {
    team: "Aswan Warriors",
    tier: "Low",
    style: "Defensive",
    players: [
      { name: "Mahmoud Galal", pos: "CB", rating: 71 },
      { name: "Hassan Nabil", pos: "CDM", rating: 70 },
      { name: "Ali Mostafa", pos: "LB", rating: 69 },
      { name: "Karim Ahmed", pos: "ST", rating: 72 },
      { name: "Tarek Fathy", pos: "GK", rating: 71 },
    ],
  },
  {
    team: "Capital United",
    tier: "Top",
    style: "Attacking",
    players: [
      { name: "Omar Salah", pos: "RW", rating: 83 },
      { name: "Ahmed Hamdy", pos: "LW", rating: 82 },
      { name: "Mostafa Nasser", pos: "CAM", rating: 84 },
      { name: "Karim Samir", pos: "CB", rating: 81 },
      { name: "Hossam Zaki", pos: "GK", rating: 83 },
    ],
  },
];

module.exports = { LEAGUE_KEY, EGYPT_LEAGUE_TEAMS };

